### ISSUE TITLE
Cannot Edit JSON from Favorite panel after theme update

### ISSUE THREAD

**Issue by Amanoki** [neuralworm/ThemeFav#2]
When a theme has been updated, in the Favorite panel, right-click > Edit JSON will not open the json file.
Not sure if it is because the file path of the theme has been changed after the update. (For example "theme-0.6" folder changes to "theme-0.7")

I will need to delete the old theme from Favorite list, add the same theme (the updated version) to Favorite again, and then the Edit JSON will open the json again from there.

Expect behavior: Edit JSON should work seamlessly and open the json file after theme updates.

**Comment by neuralworm** [comment]
Thanks again for spotting this issue. Amanoki.  This is indeed occurring as version names are changing and those changes not being properly reflected in state.  I'll get to work on a fix.

**Comment by neuralworm** [comment]
This issue should now be resolved.
